backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "noticies"
    label: "📰 Notícies"
    folder: "contingut/noticies"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Títol", name: "titol", widget: "string"}
      - {label: "Data", name: "data", widget: "datetime"}
      - {label: "Imatge", name: "imatge", widget: "image"}
      - {label: "Contingut", name: "cos", widget: "markdown"}

  - name: "textos"
    label: "✏️ Textos de la web"
    files:
      - name: "inici"
        label: "Pàgina d'inici"
        file: "contingut/inici.md"
        fields:
          - {label: "Títol de benvinguda", name: "titol", widget: "string"}
          - {label: "Text", name: "text", widget: "text"}

  - name: "galeria"
    label: "🖼️ Galeria de fotos"
    folder: "images/galeria"
    create: true
    fields:
      - {label: "Títol", name: "titol", widget: "string"}
      - {label: "Foto", name: "foto", widget: "image"}
